refactor: MVC Response 학습테스트 실패환경 구성
cho-log/spring-learning-test pull request #1
Opened 2023-11-17 09:23 UTC by Choi-JJunho

## 🚀 작업 내용

`✅ 학습 테스트 - MVC Response` 페이지를 기준으로 실패하는 테스트 환경을 구성했습니다.

## 💬 리뷰 중점사항

브랜치 생성 권한이 없어 PR에 의견 남겨봅니다!

target 브랜치를 main이 아닌 mvc-response로 하는건 어떨까요?
> 예상 브랜치 구조는 https://github.com/woowacourse/spring-learning-test 를 참고했습니다.

2023-11-24 07:14 UTC, boorownie requested changes
고생 많으셨습니다!
기존 학습 테스트에서 변경된 부분에 대해서도 코멘트를 남겨주시면 감사하겠습니다!
그리고 작업 시 README 파일도 함께 변경이 필요할 것 같아요 :)

2023-11-24 07:14 UTC, boorownie commented on spring-mvc-1/src/main/java/cholog/MemberController.java
> +public class MemberController {
혹시 컨트롤러 이름이 변경된 이유가 있을까요?

2023-11-24 07:14 UTC, boorownie commented on spring-mvc-1/src/main/java/cholog/MemberController.java
> +    }
리턴타입이 String에서 Model로 변경되었네요! 혹시 이유가 있을까요?

2023-11-24 07:14 UTC, boorownie commented on spring-mvc-1/src/main/java/cholog/MemberController.java
> +    }
요청 url도 변경이 발생했네요! 혹시 이유가 있을까요?

2023-11-24 07:14 UTC, boorownie commented on spring-mvc-1/src/test/java/cholog/ResponseTemplatesTest.java
> +    }
새로운 학습 테스트 👍

2023-11-27 06:51 UTC, Choi-JJunho commented on spring-mvc-1/src/main/java/cholog/MemberController.java
> +public class MemberController {
README 및 LMS 상에서 제시되고있는 컨트롤러 명이 MemberController여서 변경했습니다!

> LMS
<img width="866" alt="image" src="https://github.com/cho-log/spring-learning-test/assets/49794401/af258e35-3adf-46eb-94ac-7b6550fd7fd4">

다만 지금 다시 확인해보니 `/template?name=Brie` path 에 대한 테스트를 통과시키고자 하는 학습테스트가 구성되어있지 않네요!
ResponseController에 `/template?name=` path를 처리하는 예제를 다시 구성하겠습니다.

2023-11-27 06:52 UTC, Choi-JJunho commented on spring-mvc-1/src/main/java/cholog/MemberController.java
> +    }
Model을 활용하는 예제를 생각하다가 잘못 작성한 부분인 것 같습니다 😅
String으로 다시 변경하겠습니다!

2023-11-27 06:53 UTC, Choi-JJunho commented on spring-mvc-1/src/main/java/cholog/MemberController.java
> +    }
해당 부분도 마찬가지로 README 및 LMS 상에서 제시되고있는 URL path에 맞춰서 변경했습니다!

> LMS
<img width="971" alt="image" src="https://github.com/cho-log/spring-learning-test/assets/49794401/6b43bc6d-9789-453b-8f06-62e5503d51b3">

이에 `ResponseJsonTest` 테스트에 작성된 `/person` 경로 또한 `/json`으로 변경했습니다.

2023-11-27 07:15 UTC, Choi-JJunho commented
학습테스트를 확인하는 과정에서 한가지 추가 작업한 내용이 있어 코멘트 남깁니다!

<img width="976" alt="image" src="https://github.com/cho-log/spring-learning-test/assets/49794401/531cac6e-5037-4776-8a2d-bf66f2554e2a">

현재 학습테스트 중 `3. Template Engine`에서 제공하고자 하는 학습 목표는 Thymeleaf와 `@RequestParam`, `Model`을 활용하여 컨트롤러에서 뷰로 값을 전달하는 것을 목표로 하고 있는 것으로 이해했습니다.

하지만 현재 `hello.html`을 이용한 실습을 수행한다면 `@RequestParam` 혹은 `Model` 객체를 이용할 여지가 없는 상황입니다.

```html
...
<!-- 기존 hello.html -->
<body>
  Hello World!
</body>
...
```

이에 기존의 ResponseController의 `template.html` 형태를 완성하는것을 목표로 학습테스트를 구성했고 이에 기존의 `/template`를 제거했습니다.

```html
...
<!-- 변경된 hello.html, template.html 과 유사 -->
<body>
  <p th:text="'Hello, ' + ${name} + '!'" />
</body>
...
```

2023-12-11 06:18 UTC, Choi-JJunho commented
브라운 안녕하세요~! 변경된 구조에 맞춰 반영해봤습니다!

LMS 자료에 맞춰 코드를 재구성했습니다!
한가지 특이사항이 있어 따로 구분하여 코멘트 남겨봅니다!

### 특이사항
정적파일 로드와 관련하여 hello.html이 아닌 static.html을 이용하도록 문서를 변경했습니다.
기존에 `/static` 경로와 `/templates` 경로 모두 `hello.html`을 사용하다보니 학습테스트 수행 과정에서 혼동이 올 수도 있다는 우려가 있었습니다.
이에 `2 Static Page` 학습테스트에 대한 html 파일을 `hello.html`이 아닌 `static.html`으로 변경하였고 이에 대한 README 파일도 수정했습니다.

만약 반영된다면 이에 대한 **LMS 자료 수정**이 필요할 것 같아 별도로 특이사항으로 구분하여 말씀드립니다

2023-12-13 14:09 UTC, boorownie requested changes
제안 주신 부분 좋습니다! 그렇게 반영하시죠 👍 
누락된 부분이 보여서 코멘트 드립니다!

2023-12-13 14:09 UTC, boorownie commented on spring-mvc-1/initial/src/test/java/cholog/ResponseJsonTest.java
> +            .when().get("/person")
이 부분이 누락된 것 같습니다.
```suggestion
            .when().get("/json")
```

2023-12-13 14:09 UTC, boorownie commented on spring-mvc-1/initial/src/test/java/cholog/ResponseJsonTest.java
>          assertThat(response.as(Person.class).getName()).isEqualTo("Brown");
이 부분이 누락된 것 같습니다.

```suggestion
        assertThat(response.as(Person.class).getName()).isEqualTo("brown");
```

2023-12-13 14:09 UTC, boorownie commented on spring-mvc-1/complete/README.md
> +  - `resources/templates/static.html` 을 이용하여 학습 테스트를 성공시키세요.
👍

2023-12-13 14:09 UTC, boorownie commented on spring-mvc-1/initial/README.md
> +  - `resources/templates/static.html` 을 이용하여 학습 테스트를 성공시키세요.
👍

2023-12-14 04:19 UTC, boorownie approved these changes
피드백 반영 확인했습니다.
감사함니다!

2023-12-14 04:19 UTC, merged